### ISSUE TITLE
Bug in do_combine_turbulence

### ISSUE THREAD

**Issue by jbecherer** [OceanMixingGroup/chipod_gust#47] opened 2019-03-29 18:23 UTC
Hi Deepak,
there is a bug now in the new do_combine_turbulence.
it won't do ic-estimates anymore, because they don't
contain spec_floor I guess. 

   Reference to non-existent field 'spec_floor'.

   Error in do_combine_turb (line 201)
                     spec_floor = nanmedian(chi.spec_floor);
 
   Error in combine_turbulence (line 80)
   do_combine_turb(basedir, savedir, CP, do_combine, do_plot, do_mask, save_fig, is_visible)

**Comment by dcherian** [comment] 2019-03-29 18:32
Did you add `spec_area` to the ic estimates now? That's the if condition before that line is run...

**Comment by dcherian** [comment] 2019-03-29 18:36
Change the condition to `             if isempty(ic_test) & isfield(chi, 'spec_area') & isfield(chi, 'spec_floor')`

I can't reproduce locally because my IC estimates don't have spec_area.

**Comment by jbecherer** [comment] 2019-03-29 21:16
What this spec_area again? thats the integral under the curve? 
Do you think it would make sense to use Ken's Cox-number test instead?

**Comment by dcherian** [comment] 2019-03-29 21:27
> What this spec_area again? thats the integral under the curve?

Yes. 
I'm confused actually; that stuff has been in the code for a year now and wasn't changed recently. Why is this an issue now?

> Do you think it would make sense to use Ken's Cox-number test instead?

It's not a substitute, I don't think. You could have a low Cox number but not be at the instrument's noise floor (large background gradient).  ε/(νN²) would be another criterion. For low enough values (100 or so), things aren't isotropic anymore.

**Comment by jbecherer** [comment] 2019-03-29 22:28
Are you sure? I checked with a slightly older master version that is from last week I guess, which 
is the current version on ganges/work/chipod_gust
=> diff do_combine_turb.m ~/ganges/work/chipod_gust/software/main_proc/do_combine_turb.m 
564,566d563
<            if isfield(chi, 'spec_area')
<                chi.spec_area(death:end) = NaN;
<            end
584,586d580
<                if isfield(chi, 'spec_area')
<                    chi.spec_area(death:end) = NaN;
<                end
608,609d601
<    % NaN out spec_area too so that you don't overwrite NaNs with zeros if
<    % that condition is satisfied.
613,619c605,606
<            it1 = find_approx(chi.time, CP.nantimes{CP.sensor}(tt, 1), 1);
<            it2 = find_approx(chi.time, CP.nantimes{CP.sensor}(tt, 2), 1);
<            chi.chi(it1:it2) = NaN;
<            chi.eps(it1:it2) = NaN;
<            if isfield(chi, 'spec_area')
<                chi.spec_area(it1:it2) = NaN;
<            end
---
>            chi.chi(find_approx(chi.time, CP.nantimes{CP.sensor}(tt, 1), 1): ...
>                    find_approx(chi.time, CP.nantimes{CP.sensor}(tt, 2), 1)) = NaN;
620a608
>        chi.eps(isnan(chi.chi)) = NaN;
628d615
<        chi.spec_area(isnan(chi.chi)) = NaN;


SO it seems it wasn't in that version.

**Comment by jbecherer** [comment] 2019-03-29 22:30
Sorry that ended up being really bad formating. Is it possible that it was just in one of your branches for a while but not the master ???

**Comment by dcherian** [comment] 2019-03-30 00:33
Your error is from line 201. That's line 564. I did add that piece but that's not where the error is coming from

**Comment by dcherian** [comment] 2019-04-01 15:40
Ugh it affects pitot estimates. Fixed now.

**Closed as completed by dcherian** 2019-04-01 15:40 UTC
